### ISSUE TITLE
Compilation failed: internal error: previously-checked referenced subpattern not found

### ISSUE THREAD

**Issue by ontonto** [swiftmailer/swiftmailer#259]
While using swiftmailer with apache 2, php 5.4.7 (XAMPP 1.8.1) I get the following warning and fails to deliver the message:

```
preg_match(): Compilation failed: internal error: previously-checked referenced subpattern not found at offset 4246

at swiftmailer/library/classes/Swift/Mime/Headers/MailboxHeader.php on line 306
```

The regexp in question is the following:

```
/^(?:(?:(?:(?:(?:(?:(?:[ \t]*(?:\r\n))?[ \t])?(\((?:(?:(?:[ \t]*(?:\r\n))?[ \t])|(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x27\x2A-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])|(?1)))*(?:(?:[ \t]*(?:\r\n))?[ \t])?\)))*(?:(?:(?:(?:[ \t]*(?:\r\n))?[ \t])?(\((?:(?:(?:[ \t]*(?:\r\n))?[ \t])|(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x27\x2A-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])|(?1)))*(?:(?:[ \t]*(?:\r\n))?[ \t])?\)))|(?:(?:[ \t]*(?:\r\n))?[ \t])))?(?:[a-zA-Z0-9!#\$%&'\*\+\-\/=\?\^_`\{\}\|~]+(\.[a-zA-Z0-9!#\$%&'\*\+\-\/=\?\^_`\{\}\|~]+)*)+(?:(?:(?:(?:[ \t]*(?:\r\n))?[ \t])?(\((?:(?:(?:[ \t]*(?:\r\n))?[ \t])|(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x27\x2A-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])|(?1)))*(?:(?:[ \t]*(?:\r\n))?[ \t])?\)))*(?:(?:(?:(?:[ \t]*(?:\r\n))?[ \t])?(\((?:(?:(?:[ \t]*(?:\r\n))?[ \t])|(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x27\x2A-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])|(?1)))*(?:(?:[ \t]*(?:\r\n))?[ \t])?\)))|(?:(?:[ \t]*(?:\r\n))?[ \t])))?)|(?:(?:(?:(?:(?:[ \t]*(?:\r\n))?[ \t])?(\((?:(?:(?:[ \t]*(?:\r\n))?[ \t])|(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x27\x2A-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])|(?1)))*(?:(?:[ \t]*(?:\r\n))?[ \t])?\)))*(?:(?:(?:(?:[ \t]*(?:\r\n))?[ \t])?(\((?:(?:(?:[ \t]*(?:\r\n))?[ \t])|(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x27\x2A-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])|(?1)))*(?:(?:[ \t]*(?:\r\n))?[ \t])?\)))|(?:(?:[ \t]*(?:\r\n))?[ \t])))?"((?:(?:[ \t]*(?:\r\n))?[ \t])?(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21\x23-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])))*(?:(?:[ \t]*(?:\r\n))?[ \t])?"(?:(?:(?:(?:[ \t]*(?:\r\n))?[ \t])?(\((?:(?:(?:[ \t]*(?:\r\n))?[ \t])|(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x27\x2A-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])|(?1)))*(?:(?:[ \t]*(?:\r\n))?[ \t])?\)))*(?:(?:(?:(?:[ \t]*(?:\r\n))?[ \t])?(\((?:(?:(?:[ \t]*(?:\r\n))?[ \t])|(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x27\x2A-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])|(?1)))*(?:(?:[ \t]*(?:\r\n))?[ \t])?\)))|(?:(?:[ \t]*(?:\r\n))?[ \t])))?))@(?:(?:(?:(?:(?:(?:[ \t]*(?:\r\n))?[ \t])?(\((?:(?:(?:[ \t]*(?:\r\n))?[ \t])|(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x27\x2A-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])|(?1)))*(?:(?:[ \t]*(?:\r\n))?[ \t])?\)))*(?:(?:(?:(?:[ \t]*(?:\r\n))?[ \t])?(\((?:(?:(?:[ \t]*(?:\r\n))?[ \t])|(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x27\x2A-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])|(?1)))*(?:(?:[ \t]*(?:\r\n))?[ \t])?\)))|(?:(?:[ \t]*(?:\r\n))?[ \t])))?(?:[a-zA-Z0-9!#\$%&'\*\+\-\/=\?\^_`\{\}\|~]+(\.[a-zA-Z0-9!#\$%&'\*\+\-\/=\?\^_`\{\}\|~]+)*)+(?:(?:(?:(?:[ \t]*(?:\r\n))?[ \t])?(\((?:(?:(?:[ \t]*(?:\r\n))?[ \t])|(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x27\x2A-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])|(?1)))*(?:(?:[ \t]*(?:\r\n))?[ \t])?\)))*(?:(?:(?:(?:[ \t]*(?:\r\n))?[ \t])?(\((?:(?:(?:[ \t]*(?:\r\n))?[ \t])|(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x27\x2A-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])|(?1)))*(?:(?:[ \t]*(?:\r\n))?[ \t])?\)))|(?:(?:[ \t]*(?:\r\n))?[ \t])))?)|(?:(?:(?:(?:(?:[ \t]*(?:\r\n))?[ \t])?(\((?:(?:(?:[ \t]*(?:\r\n))?[ \t])|(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x27\x2A-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])|(?1)))*(?:(?:[ \t]*(?:\r\n))?[ \t])?\)))*(?:(?:(?:(?:[ \t]*(?:\r\n))?[ \t])?(\((?:(?:(?:[ \t]*(?:\r\n))?[ \t])|(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x27\x2A-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])|(?1)))*(?:(?:[ \t]*(?:\r\n))?[ \t])?\)))|(?:(?:[ \t]*(?:\r\n))?[ \t])))?\[((?:(?:[ \t]*(?:\r\n))?[ \t])?(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x5A\x5E-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])))*?(?:(?:[ \t]*(?:\r\n))?[ \t])?\](?:(?:(?:(?:[ \t]*(?:\r\n))?[ \t])?(\((?:(?:(?:[ \t]*(?:\r\n))?[ \t])|(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x27\x2A-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])|(?1)))*(?:(?:[ \t]*(?:\r\n))?[ \t])?\)))*(?:(?:(?:(?:[ \t]*(?:\r\n))?[ \t])?(\((?:(?:(?:[ \t]*(?:\r\n))?[ \t])|(?:(?:[\x01-\x08\x0B\x0C\x0E-\x19\x7F]|[\x21-\x27\x2A-\x5B\x5D-\x7E])|(?:\\[\x00-\x08\x0B\x0C\x0E-\x7F])|(?1)))*(?:(?:[ \t]*(?:\r\n))?[ \t])?\)))|(?:(?:[ \t]*(?:\r\n))?[ \t])))?))))$/D
```

The problem only occurs when the page is served through apache. When I run a copy the regexp to a test file and validate against that, it does not issue the warning.

I have temporarily "solved" the problem by removing the validation altogether. However, I hope there is a better solution.

Thank you!

**Comment by mzur** [comment]
Is there now any news on this? I'm currently experiencing this error with my Laravel application and am desperately searching for the cause. It seems to appear only with certain configurations involving an Apache. My setup runs recent versions of PHP, Apache and PRCE but the error still persists.

**Comment by smelchior** [comment]
Is there any update on this? We are currently experiencing this issue with the current 5.6.9 dotdeb packages. In 5.6.9 the PCRE Version was updated to 8.37 (http://php.net/ChangeLog-5.php#5.6.9) and this does not seem to play well with the swiftmailer regex.

**Comment by cpocholle** [comment]
Anyone solved the problem ? I have this erreur after a recent apt-get update on my server.

**Comment by eliecharra** [comment]
up

**Comment by dmaicher** [comment]
I just downloaded and compiled libpcre 8.37 and the swiftmailer regex works just fine using pcregrep. So I think the issue is more likely to be with php or apache2 itself? Some weird libpcre mismatch or something... not sure :(

**Comment by liayn** [comment]
Just a hint from the TYPO3 world: https://forge.typo3.org/issues/67048

We face the same issue. Affected PHP versions seem to be 5.6.9, 5.5.25 and 5.4.41
This bug crashes the whole template engine Fluid in our case!

**Comment by xdecock** [comment]
Nice job altough hard to fix from here :(

But swift 6 will work with emailchecker

**Comment by mzur** [comment]
To check if you have mismatching versions of PCRE between the system library and PHP you can run `pcretest -C` and `php -i | grep PCRE`. If the versions don't match, this is likely the cause of the error.

I'll ask the support of my hoster what exactly they did to make the versions match and report back later.

**Comment by liayn** [comment]
As noted in https://bugs.php.net/bug.php?id=69689 obviously they messed up the version number as well and PHP reports a wrong version number.

**Comment by mzur** [comment]
My hoster solved the version mismatch by rebuilding PHP using the [`configure`](http://www.linuxfromscratch.org/blfs/view/svn/general/php.html) script with `--with-pcre-regex=/usr`. A PHP upgrade might fix this issue as well.

**Comment by sangar82** [comment]
My hoster solves the situation downgrading the php version to 5.5.24. Good work!

**Comment by samwierema** [comment]
Seems to have been fixed in source: https://github.com/php/php-src/commit/f38ca75a3cc5737bdb922dc5e2a7505cd20cd7ea

**Comment by JanTvrdik** [comment]
Can anyone confirm this has been resolved with the latest snapshot?

**Comment by gnutix** [comment]
I just hit the same bug today using PHP 5.5.25-1~dotdeb+7.1. Hope it's resolved as well. :(

**Comment by gnutix** [comment]
I updated my PHP version to PHP 5.6.9-1~dotdeb+7.2 and I still get this bug.

**Comment by dseguy** [comment]
Thanks to this threads I fixed a similar problem in my WP installation.

**Comment by xkobal** [comment]
Same with 5.5.25 and 5.6.10 from dotdeb

**Comment by xdecock** [comment]
And 5.6.9 ?  Or a self build ?  It was an error in packaging basically the
bundled pcrelib is only partially updated

Le ven. 12 juin 2015 14:14, Xavier HAUSHERR <notifications@github.com> a
écrit :

**Comment by xkobal** [comment]
Seems to be a packaging bug indeed: 

root@jfg-stage-internal-1:~# php -v
PHP 5.6.10-1~dotdeb+7.1 (cli) (built: Jun 11 2015 20:38:39) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
root@jfg-stage-internal-1:~# php -i | grep PCRE
PCRE (Perl Compatible Regular Expressions) Support => enabled
PCRE Library Version => 8.36 2014-09-26


PHP changelog show 8.37...

**Comment by xdecock** [comment]
It's not the first time unfortunately and we got the bug reports everytime

Le ven. 12 juin 2015 14:20, Xavier HAUSHERR <notifications@github.com> a
écrit :

**Comment by gplessis** [comment]
It's not a packaging issue, `PCRE_MINOR` hasn't been changed correctly in PHP upstream. I'm currently building packages of PHP 5.6, 5.5 and 5.4 with this cosmetic change. Stay tuned.

https://github.com/gplessis/dotdeb-php5/commit/f3749b75f65e4ff20a3419b706d0a077892b990d

BTW, that's just a cosmetic change, not sure if it solves your original issue. Please keep me posted.

**Comment by gplessis** [comment]
Guys, I just uploaded new PHP 5.6 packages (versions `5.6.10-1~dotdeb+7.2` and `5.6.10-1~dotdeb+zts+7.2`). Could you please confirm that PCRE 8.37 is displayed? If so, does it fixes your original issue?

**Comment by dmaicher** [comment]
Thx for the update. Now the version looks correct:

```
php -v
PHP 5.6.10-1~dotdeb+7.2 (cli) (built: Jun 13 2015 20:08:39) 

php -i | grep PCRE
PCRE Library Version => 8.37 2015-04-28
```

Unfortunately the original problem with the swiftmailer regex using apache2 mod php stays the same :(

**Comment by gplessis** [comment]
I just uploaded new PHP 5.6 packages (versions 5.6.10-1~dotdeb+7.3 and 5.6.10-1~dotdeb+zts+7.3) that fix your issue.

**Comment by Zeromax** [comment]
@gplessis thanks, this fixed it for me.

**Comment by dseguy** [comment]
Thanks @gplessis. Works wonder here.
