### ISSUE TITLE
Address in mailbox given does not comply with RFC 2822, 3.6.2.

### ISSUE THREAD

**Issue by fabienlege** [swiftmailer/swiftmailer#382]
When i try to send a newsletter i have this error :
Address in mailbox given [agence-immobiliere-aaaaaaaa@wanadoo.fr ] does not comply with RFC 2822, 3.6.2.

I don't understand what is wrong because this address realy exist...

**Comment by SashaDesigN** [comment]
its didnt help me

**Comment by SashaDesigN** [comment]
Its help me - before send message I do mysql_real_escape_string()

**Comment by truckee** [comment]
In a Symfony 2.6.4 application, a custom config parameter `admin_email: admin@bogus.info` throws the above referenced error when the parameter is defined inside the bundle.  If the parameter is instead added to `parameters.yml` (and parameters.yml.dist) and no custom configuration appears in the bundle the error is NOT thrown.  The error is not dependent on validity or compliance of the e-mail address.  For example, truckeesolutions@gmail.com is not considered compliant.

The custom parameter was moved from `parameters.yml` to satisfy the Sensio Insight constraint that only default parameters from parameters.yml.dist are allowed.

**Comment by LouTerrailloune** [comment]
For googlers, I had the same issue. The problem was the PCRE lib version used by the mod_php which dont want to compile the regex used by swiftmailer to check addresses. (there is a warning the the php logs).

**Comment by bastianmartin** [comment]
Lou: which one did you use? Thanks!

**Comment by LouTerrailloune** [comment]
@bastianmartin I did not change the pcre lib because I dont have the right on the server. I just made an ugly fork and removed the check. See LouTerrailloune/swiftmailer@d71ecbb35c33aaf8de4dfd5f2e1167cbe3383187 .

**Comment by bastianmartin** [comment]
@LouTerrailloune Thank you! I'm trying to update PHP libs - maybe it was already fixed. Otherwise I'm gonna comment that too... damn ;-)

**Comment by LouTerrailloune** [comment]
I still have some warnings in the logs, be carefull.
An interesting post: http://stackoverflow.com/questions/15963755/swift-rfccomplianceexception-on-valid-email-address-works-in-windows-not-in-ubu

**Comment by bastianmartin** [comment]
Thanks - I've updated PHP to the latest DotDeb Build (5.6.10) and the issue is gone.

**Comment by Pierstoval** [comment]
Why not change this code:

```php
if (!preg_match('/^' . $this->getGrammar('addr-spec') . '$/D', $address))
```

With this:

```php
if (0 === preg_match('/^' . $this->getGrammar('addr-spec') . '$/D', $address))
```

Then, any `false` will throw a classical error that will not break up the entire application. 
Could also add a `@` right before `preg_match` to be sure no error is thrown.

**Comment by rameezrami** [comment]
plz make sure there is no white space before or after the email address given

**Comment by Pierstoval** [comment]
It's your role to use `trim` on the email address before sending it to Swiftmailer, I think

**Comment by bastianmartin** [comment]
In my case, PHP was the culprit. After updating to 5.6.10 (without changing the existing PHP code) the issue was gone. However, I also think that Swiftmailer should use `trim` on the addresses.

**Comment by obense** [comment]
In my case, it works after updating PHP from 5.5.25 to 5.5.28.

**Comment by arshdeep79** [comment]
> t

**Comment by imcaffrey** [comment]
In my case, im using PHP 5.6.18, facing the same error message.

**Comment by wyklif** [comment]
in my case it was a blank bcc

**Comment by sa3dwi** [comment]
i used iconv() and trim() to fix this issue

**Comment by SashaDesigN** [comment]
trim() helps me too ^^)

**Comment by ventoh** [comment]
same error here. Trim not helped me. This are the emails that throw the error:

célian.schmitt@example.com
nathanaël.riviere@example.com

Really i don't want to send those emails, it's just a simulation, but this error break it.
any hint?

**Comment by kir86975** [comment]
Hello! I can't to send any e-mail with addresses пример@пример.рф or example@пример.рф and get the same error. Google supports this addresses. Why are you not support it?

**Comment by naffiq** [comment]
Hello!

Seems like an old issue, but I don't know where to post this.

I'm using mailgun.com service, and there is a feature of batch sending emails, by defining receiver as `%recipient%` and adding header, containing recipients data.

It would be great, if there would be a way to redefine Swift_Mime_Grammar as DI and create interface for it?

**Comment by fabpot** [comment]
Closing as the email validation is now done by an external library that you can configure (Swiftmailer 6+).

**Comment by gondo** [comment]
@fabpot how can you configure this external library? link to documentation or an example would be extremely helpful 
see #999

**Comment by ozhala** [comment]
Work for me just fine
        $trim_ = trim($email);
        $filter_var = filter_var($trim, FILTER_SANITIZE_EMAIL);
        $iconv = iconv('ISO-8859-1','UTF-8//IGNORE', $filter_var);

**Comment by stasionok** [comment]
> Hello! I can't to send any e-mail with addresses пример@пример.рф or example@пример.рф and get the same error. Google supports this addresses. Why are you not support it?

You should convert your пример.рф  domain into IDNA format like 'xn--e1afmkfd.xn--p1ai'

**Comment by safiullahsarhandi** [comment]
i was also getting this problem when i was sending multiple emails at a time and there was email duplication passed in bcc , to , CC methods 

`$message->to('abc@gmail.com')->bcc(['abc@gmail.com','johndoe@gmail.com']);`

**Comment by Acksop** [comment]
Simply change :+1: 
    ```
$email = new Swift_Message();
    $email->setSender(array('xxxxxxx@xxxxxxx.xxx' => "Le ROBOT-gueulard(t) du (B25)"));
```
and
swiftmailer-5.x/lib/classes/Swift/Message.php at line 46 by
           ` array($this, 'Swift_Message::__construct'),`
instead of
           ` array($this, 'Swift_Mime_SimpleMessage::__construct'),`

**Comment by abardik** [comment]
For me, it was empty email address sent to setReplyTo(). Fixed by not calling this method if reply-to is absent. I think, the same would be with setFrom, setCc, setBcc.

**Comment by ttuchtfeldt** [comment]
In my case it was a blank bcc, too!

**Comment by drudriger** [comment]
In my case was empty "To Name"
it was
`$message->setTo(['my@email.to'])`
and need be
`$message->setTo(['my@email.to' => 'my name'])`

**Comment by yii2backendwebdeveloper** [comment]
> in my case it was a blank bcc
Your comment should be on top somewhere

**Comment by clarcked** [comment]
This looks like a very old question. Recently, I've got an error like this because i have put the email address in the name argument and vice versa. Maybe this comment can help someone...
